package koulutusRekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import koulutusRekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.05.20 16:50:54 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class KoulutusTest {


  // Generated by ComTest BEGIN
  /** testGetKoulutus76 */
  @Test
  public void testGetKoulutus76() {    // Koulutus: 76
    Koulutus vesi = new Koulutus(); 
    vesi.vastaaVesisukeltaja(); 
    { String _l_=vesi.getKoulutus(),_r_="Vesisukeltaja"; if ( !_l_.matches(_r_) ) fail("From: Koulutus line: 79" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi119 */
  @Test
  public void testRekisteroi119() {    // Koulutus: 119
    Koulutus vesi1 = new Koulutus(); 
    assertEquals("From: Koulutus line: 121", 0, vesi1.getKoulutusTunnus()); 
    vesi1.rekisteroi(); 
    Koulutus vesi2 = new Koulutus(); 
    vesi2.rekisteroi(); 
    int n1 = vesi1.getKoulutusTunnus(); 
    int n2 = vesi2.getKoulutusTunnus(); 
    assertEquals("From: Koulutus line: 127", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString154 */
  @Test
  public void testToString154() {    // Koulutus: 154
    Koulutus koulutus = new Koulutus(); 
    koulutus.parse(" 1  | Vesisukeltaja  "); 
    assertEquals("From: Koulutus line: 157", "1|Vesisukeltaja", koulutus.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse172 */
  @Test
  public void testParse172() {    // Koulutus: 172
    Koulutus koulutus = new Koulutus(); 
    koulutus.parse("1|Vesisukeltaja"); 
    assertEquals("From: Koulutus line: 175", 1, koulutus.getKoulutusTunnus()); 
    assertEquals("From: Koulutus line: 176", "1|Vesisukeltaja", koulutus.toString()); 
    koulutus.rekisteroi(); 
    int n = koulutus.getKoulutusTunnus(); 
    koulutus.parse(""+(n+20)); 
    koulutus.rekisteroi(); 
    assertEquals("From: Koulutus line: 182", n+20+1, koulutus.getKoulutusTunnus()); 
  } // Generated by ComTest END
}