package koulutusRekisteri.test;
// Generated by ComTest BEGIN
import java.util.*;
import java.io.*;
import static org.junit.Assert.*;
import org.junit.*;
import koulutusRekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.05.25 18:46:36 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class KoulutusrekisteriTest {

  // Generated by ComTest BEGIN  // Koulutusrekisteri: 38
   private Koulutusrekisteri koulutusrekisteri; 
   private Tyontekija aku1; 
   private Tyontekija aku2; 
   private int jid1; 
   private int jid2; 
   private Koulutus pitsi21; 
   private Koulutus pitsi11; 
   private Koulutus pitsi22; 
   private Koulutus pitsi12; 
   private Koulutus pitsi23; 
   private Relaatio rel1; 

   public void alusta() {
     koulutusrekisteri = new Koulutusrekisteri(); 
     aku1 = new Tyontekija(); aku1.vastaaAkuAnkka(); aku1.rekisteroi(); 
     aku2 = new Tyontekija(); aku2.vastaaAkuAnkka(); aku2.rekisteroi(); 
     jid1 = aku1.getTyontekijaTunnus(); 
     jid2 = aku2.getTyontekijaTunnus(); 
     pitsi21 = new Koulutus(jid2); pitsi21.vastaaVesisukeltaja(); 
     pitsi11 = new Koulutus(jid1); pitsi11.vastaaVesisukeltaja(); 
     pitsi22 = new Koulutus(jid2); pitsi22.vastaaVesisukeltaja(); 
     pitsi12 = new Koulutus(jid1); pitsi12.vastaaVesisukeltaja(); 
     pitsi23 = new Koulutus(jid2); pitsi23.vastaaVesisukeltaja(); 
     try {
     koulutusrekisteri.lisaa(aku1); 
     koulutusrekisteri.lisaa(aku2); 
     koulutusrekisteri.lisaa(pitsi21); 
     koulutusrekisteri.lisaa(pitsi11); 
     koulutusrekisteri.lisaa(pitsi22); 
     koulutusrekisteri.lisaa(pitsi12); 
     koulutusrekisteri.lisaa(pitsi23); 
     } catch ( Exception e) {
        System.err.println(e.getMessage()); 
     }
   }
  // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoistaTyontekijanKoulutus87 
   * @throws Exception when error
   */
  @Test
  public void testPoistaTyontekijanKoulutus87() throws Exception {    // Koulutusrekisteri: 87
    alusta(); 
    Koulutusrekisteri koulutusrekisteri = new Koulutusrekisteri(); 
    Tyontekija aku1 = new Tyontekija(); aku1.vastaaAkuAnkka(); aku1.rekisteroi(); 
    Tyontekija aku2 = new Tyontekija(); aku2.vastaaAkuAnkka(); aku2.rekisteroi(); 
    Tyontekija aku3 = new Tyontekija(); aku3.vastaaAkuAnkka(); aku3.rekisteroi(); 
    Koulutus vesi1 = new Koulutus(); vesi1.vastaaVesisukeltaja(); vesi1.rekisteroi(); 
    Koulutus vesi2 = new Koulutus(); vesi2.vastaaVesisukeltaja(); vesi2.rekisteroi(); 
    int id1 = aku1.getTyontekijaTunnus(); 
    int id2 = aku2.getTyontekijaTunnus(); 
    int id3 = vesi1.getKoulutusTunnus(); 
    int id4 = vesi2.getKoulutusTunnus(); 
    String id5 = vesi1.getKoulutus(); 
    String id6 = vesi2.getKoulutus(); 
    Relaatio rel1 = new Relaatio(id1, id3, id5); rel1.vastaaRelaatio(); rel1.rekisteroi(); 
    Relaatio rel2 = new Relaatio(id2, id4, id6); rel2.vastaaRelaatio(); rel2.rekisteroi(); 
    assertEquals("From: Koulutusrekisteri line: 110", 2, koulutusrekisteri.annaRelaatiot(1).size()); 
    koulutusrekisteri.poistaTyontekijanKoulutus(rel1); 
    assertEquals("From: Koulutusrekisteri line: 112", 1, koulutusrekisteri.annaRelaatiot(2).size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLisaa152 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa152() throws SailoException {    // Koulutusrekisteri: 152
    Koulutusrekisteri koulutusrekisteri = new Koulutusrekisteri(); 
    Tyontekija aku1 = new Tyontekija(), aku2 = new Tyontekija(); 
    koulutusrekisteri.lisaa(aku1); 
    koulutusrekisteri.lisaa(aku2); 
    koulutusrekisteri.lisaa(aku1); 
    Collection<Tyontekija> loytyneet = koulutusrekisteri.etsiTyontekija("", -1); 
    Iterator<Tyontekija> it = loytyneet.iterator(); 
    assertEquals("From: Koulutusrekisteri line: 161", aku1, it.next()); 
    assertEquals("From: Koulutusrekisteri line: 162", aku2, it.next()); 
    assertEquals("From: Koulutusrekisteri line: 163", aku1, it.next()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testEtsiTyontekija199 
   * @throws CloneNotSupportedException when error
   * @throws SailoException when error
   */
  @Test
  public void testEtsiTyontekija199() throws CloneNotSupportedException, SailoException {    // Koulutusrekisteri: 199
    alusta(); 
    Tyontekijat tyontekijat = new Tyontekijat(); 
    Tyontekija jasen3 = new Tyontekija(); jasen3.rekisteroi(); 
    tyontekijat.korvaaTaiLisaa(jasen3); 
    koulutusrekisteri.lisaa(jasen3); 
    Collection<Tyontekija> loytyneet = koulutusrekisteri.etsiTyontekija("*Susi*",1); 
    assertEquals("From: Koulutusrekisteri line: 207", 1, loytyneet.size()); 
    Iterator<Tyontekija> it = loytyneet.iterator(); 
    assertEquals("From: Koulutusrekisteri line: 209", true, it.next() == jasen3); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testAnnaRelaatiot269 
   * @throws IndexOutOfBoundsException when error
   */
  @Test
  public void testAnnaRelaatiot269() throws IndexOutOfBoundsException {    // Koulutusrekisteri: 269
    Koulutusrekisteri koulutusrekisteri = new Koulutusrekisteri(); 
    Tyontekija aku1 = new Tyontekija(); aku1.vastaaAkuAnkka(); aku1.rekisteroi(); 
    Tyontekija aku2 = new Tyontekija(); aku2.vastaaAkuAnkka(); aku2.rekisteroi(); 
    Tyontekija aku3 = new Tyontekija(); aku3.vastaaAkuAnkka(); aku3.rekisteroi(); 
    Koulutus vesi1 = new Koulutus(); vesi1.vastaaVesisukeltaja(); vesi1.rekisteroi(); 
    Koulutus vesi2 = new Koulutus(); vesi2.vastaaVesisukeltaja(); vesi2.rekisteroi(); 
    int id1 = aku1.getTyontekijaTunnus(); 
    int id2 = aku2.getTyontekijaTunnus(); 
    int id3 = vesi1.getKoulutusTunnus(); 
    int id4 = vesi2.getKoulutusTunnus(); 
    String id5 = vesi1.getKoulutus(); 
    String id6 = vesi2.getKoulutus(); 
    Relaatio rel1 = new Relaatio(id1, id3, id5); rel1.vastaaRelaatio(); rel1.rekisteroi(); 
    Relaatio rel2 = new Relaatio(id2, id4, id6); rel2.vastaaRelaatio(); rel2.rekisteroi(); 
    try {
    koulutusrekisteri.lisaa(aku1); 
    fail("Koulutusrekisteri: 293 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    try {
    koulutusrekisteri.lisaa(aku2); 
    fail("Koulutusrekisteri: 294 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    try {
    koulutusrekisteri.lisaa(vesi1); 
    fail("Koulutusrekisteri: 295 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    try {
    koulutusrekisteri.lisaa(vesi2); 
    fail("Koulutusrekisteri: 296 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    try {
    koulutusrekisteri.lisaa(rel1); 
    fail("Koulutusrekisteri: 297 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    try {
    koulutusrekisteri.lisaa(rel2); 
    fail("Koulutusrekisteri: 298 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    List<Relaatio> loytyneet; 
    loytyneet = koulutusrekisteri.annaRelaatiot(1); 
    assertEquals("From: Koulutusrekisteri line: 302", 1, loytyneet.size()); 
    loytyneet = koulutusrekisteri.annaRelaatiot(2); 
    assertEquals("From: Koulutusrekisteri line: 304", 2, loytyneet.size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta334 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta334() throws SailoException {    // Koulutusrekisteri: 334
    Koulutusrekisteri koulutusrekisteri = new Koulutusrekisteri(); 
    Tyontekija aku1 = new Tyontekija(); aku1.vastaaAkuAnkka(); aku1.rekisteroi(); 
    Tyontekija aku2 = new Tyontekija(); aku2.vastaaAkuAnkka(); aku2.rekisteroi(); 
    Koulutus vesi1 = new Koulutus(); vesi1.vastaaVesisukeltaja(); vesi1.rekisteroi(); 
    Koulutus vesi2 = new Koulutus(); vesi2.vastaaVesisukeltaja(); vesi2.rekisteroi(); 
    int id1 = aku1.getTyontekijaTunnus(); 
    int id2 = aku2.getTyontekijaTunnus(); 
    int id3 = vesi1.getKoulutusTunnus(); 
    int id4 = vesi2.getKoulutusTunnus(); 
    String id5 = vesi1.getKoulutus(); 
    String id6 = vesi2.getKoulutus(); 
    Relaatio rel1 = new Relaatio(id1, id3, id5); rel1.vastaaRelaatio(); rel1.rekisteroi(); 
    Relaatio rel2 = new Relaatio(id2, id4, id6); rel2.vastaaRelaatio(); rel2.rekisteroi(); 
    String hakemisto = "testit"; 
    File dir = new File(hakemisto); 
    File ftied = new File(hakemisto+"/tyontekijat.dat"); 
    File fktied = new File(hakemisto+"/koulutukset.dat"); 
    File frtied = new File(hakemisto+"/relaatiot.dat"); 
    dir.mkdir(); 
    ftied.delete(); 
    fktied.delete(); 
    frtied.delete(); 
    try {
    koulutusrekisteri.lueTiedostosta(hakemisto); 
    fail("Koulutusrekisteri: 366 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    koulutusrekisteri.lisaa(aku1); 
    koulutusrekisteri.lisaa(aku2); 
    koulutusrekisteri.lisaa(vesi1); 
    koulutusrekisteri.lisaa(vesi2); 
    koulutusrekisteri.lisaa(rel1); 
    koulutusrekisteri.lisaa(rel2); 
    koulutusrekisteri.tallenna(); 
    koulutusrekisteri = new Koulutusrekisteri(); 
    koulutusrekisteri.lueTiedostosta(hakemisto); 
    Collection<Tyontekija> kaikki = koulutusrekisteri.etsiTyontekija("", -1); 
    Iterator<Tyontekija> it = kaikki.iterator(); 
    assertEquals("From: Koulutusrekisteri line: 381", aku1, it.next()); 
    assertEquals("From: Koulutusrekisteri line: 382", aku2, it.next()); 
    assertEquals("From: Koulutusrekisteri line: 383", false, it.hasNext()); 
    Collection<Koulutus> koulutus = koulutusrekisteri.etsiKoulutus("", -1); 
    Iterator<Koulutus> ik = koulutus.iterator(); 
    assertEquals("From: Koulutusrekisteri line: 387", vesi1, ik.next()); 
    assertEquals("From: Koulutusrekisteri line: 388", vesi2, ik.next()); 
    assertEquals("From: Koulutusrekisteri line: 389", false, ik.hasNext()); 
    List<Relaatio> loytyneet = koulutusrekisteri.annaRelaatiot(0); 
    Iterator<Relaatio> ir = loytyneet.iterator(); 
    assertEquals("From: Koulutusrekisteri line: 393", rel1, ir.next()); 
    assertEquals("From: Koulutusrekisteri line: 394", rel2, ir.next()); 
    assertEquals("From: Koulutusrekisteri line: 395", false, ir.hasNext()); 
    loytyneet = koulutusrekisteri.annaRelaatiot(1); 
    ir = loytyneet.iterator(); 
    assertEquals("From: Koulutusrekisteri line: 398", rel1, ir.next()); 
    assertEquals("From: Koulutusrekisteri line: 399", rel2, ir.next()); 
    assertEquals("From: Koulutusrekisteri line: 400", false, ir.hasNext()); 
    koulutusrekisteri.lisaa(aku1); 
    koulutusrekisteri.lisaa(vesi1); 
    koulutusrekisteri.lisaa(rel1); 
    koulutusrekisteri.tallenna(); 
    assertEquals("From: Koulutusrekisteri line: 405", true, ftied.delete()); 
    assertEquals("From: Koulutusrekisteri line: 406", true, fktied.delete()); 
    assertEquals("From: Koulutusrekisteri line: 407", true, frtied.delete()); 
    assertEquals("From: Koulutusrekisteri line: 408", true, dir.delete()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testKorvaaTaiLisaa457 
   * @throws SailoException when error
   */
  @Test
  public void testKorvaaTaiLisaa457() throws SailoException {    // Koulutusrekisteri: 457
    alusta(); 
    assertEquals("From: Koulutusrekisteri line: 460", 2, koulutusrekisteri.etsiTyontekija("*",0).size()); 
    koulutusrekisteri.korvaaTaiLisaa(aku1); 
    assertEquals("From: Koulutusrekisteri line: 462", 2, koulutusrekisteri.etsiTyontekija("*",0).size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testKorvaaTaiLisaa476 
   * @throws SailoException when error
   */
  @Test
  public void testKorvaaTaiLisaa476() throws SailoException {    // Koulutusrekisteri: 476
    alusta(); 
    assertEquals("From: Koulutusrekisteri line: 479", 2, koulutusrekisteri.etsiKoulutus("*",0).size()); 
    koulutusrekisteri.korvaaTaiLisaa(pitsi21); 
    assertEquals("From: Koulutusrekisteri line: 481", 2, koulutusrekisteri.etsiKoulutus("*",0).size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testKorvaaTaiLisaa495 
   * @throws SailoException when error
   */
  @Test
  public void testKorvaaTaiLisaa495() throws SailoException {    // Koulutusrekisteri: 495
    alusta(); 
    assertEquals("From: Koulutusrekisteri line: 498", 2, koulutusrekisteri.etsiRelaatio("*",0).size()); 
    koulutusrekisteri.korvaaTaiLisaa(rel1); 
    assertEquals("From: Koulutusrekisteri line: 500", 2, koulutusrekisteri.etsiRelaatio("*",0).size()); 
  } // Generated by ComTest END
}