package koulutusRekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import koulutusRekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.05.26 19:47:34 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class KoulutusTest {


  // Generated by ComTest BEGIN
  /** testGetKoulutus90 */
  @Test
  public void testGetKoulutus90() {    // Koulutus: 90
    Koulutus vesi = new Koulutus(); 
    vesi.vastaaVesisukeltaja(); 
    { String _l_=vesi.getKoulutus(),_r_="Vesisukeltaja"; if ( !_l_.matches(_r_) ) fail("From: Koulutus line: 93" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi132 */
  @Test
  public void testRekisteroi132() {    // Koulutus: 132
    Koulutus vesi1 = new Koulutus(); 
    assertEquals("From: Koulutus line: 134", 0, vesi1.getKoulutusTunnus()); 
    vesi1.rekisteroi(); 
    Koulutus vesi2 = new Koulutus(); 
    vesi2.rekisteroi(); 
    int n1 = vesi1.getKoulutusTunnus(); 
    int n2 = vesi2.getKoulutusTunnus(); 
    assertEquals("From: Koulutus line: 140", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString167 */
  @Test
  public void testToString167() {    // Koulutus: 167
    Koulutus koulutus = new Koulutus(); 
    koulutus.parse(" 1  | Vesisukeltaja  "); 
    assertEquals("From: Koulutus line: 170", "1|Vesisukeltaja", koulutus.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse185 */
  @Test
  public void testParse185() {    // Koulutus: 185
    Koulutus koulutus = new Koulutus(); 
    koulutus.parse("1|Vesisukeltaja"); 
    assertEquals("From: Koulutus line: 188", 1, koulutus.getKoulutusTunnus()); 
    assertEquals("From: Koulutus line: 189", "1|Vesisukeltaja", koulutus.toString()); 
    koulutus.rekisteroi(); 
    int n = koulutus.getKoulutusTunnus(); 
    koulutus.parse(""+(n+20)); 
    koulutus.rekisteroi(); 
    assertEquals("From: Koulutus line: 195", n+20+1, koulutus.getKoulutusTunnus()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone209 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone209() throws CloneNotSupportedException {    // Koulutus: 209
    Koulutus koulutus = new Koulutus(); 
    koulutus.parse("   1  |  Vesisukeltaja "); 
    try {
    Koulutus kopio = koulutus.clone(); 
    assertEquals("From: Koulutus line: 215", koulutus.toString(), kopio.toString()); 
    koulutus.parse("   2  |  Vesisukeltaja "); 
    assertEquals("From: Koulutus line: 217", false, kopio.toString().equals(koulutus.toString())); 
    } catch (CloneNotSupportedException e) {
    System.err.println(e.getMessage()); 
    }
  } // Generated by ComTest END
}