package koulutusRekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import koulutusRekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.05.05 18:11:03 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class KoulutusTest {


  // Generated by ComTest BEGIN
  /** testGetKoulutus77 */
  @Test
  public void testGetKoulutus77() {    // Koulutus: 77
    Koulutus vesi = new Koulutus(); 
    vesi.vastaaVesisukeltaja(); 
    { String _l_=vesi.getKoulutus(),_r_="Vesisukeltaja .*"; if ( !_l_.matches(_r_) ) fail("From: Koulutus line: 80" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi120 */
  @Test
  public void testRekisteroi120() {    // Koulutus: 120
    Koulutus vesi1 = new Koulutus(); 
    assertEquals("From: Koulutus line: 122", 0, vesi1.getKoulutusTunnus()); 
    vesi1.rekisteroi(); 
    Koulutus vesi2 = new Koulutus(); 
    vesi2.rekisteroi(); 
    int n1 = vesi1.getKoulutusTunnus(); 
    int n2 = vesi2.getKoulutusTunnus(); 
    assertEquals("From: Koulutus line: 128", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString155 */
  @Test
  public void testToString155() {    // Koulutus: 155
    Koulutus koulutus = new Koulutus(); 
    koulutus.parse(" 1  | Vesisukeltaja  "); 
    assertEquals("From: Koulutus line: 158", "1|Vesisukeltaja", koulutus.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse173 */
  @Test
  public void testParse173() {    // Koulutus: 173
    Koulutus koulutus = new Koulutus(); 
    koulutus.parse("1|Vesisukeltaja"); 
    assertEquals("From: Koulutus line: 176", 1, koulutus.getKoulutusTunnus()); 
    assertEquals("From: Koulutus line: 177", "1|Vesisukeltaja", koulutus.toString()); 
    koulutus.rekisteroi(); 
    int n = koulutus.getKoulutusTunnus(); 
    koulutus.parse(""+(n+20)); 
    koulutus.rekisteroi(); 
    assertEquals("From: Koulutus line: 183", n+20+1, koulutus.getKoulutusTunnus()); 
  } // Generated by ComTest END
}