package koulutusRekisteri.test;
// Generated by ComTest BEGIN
import java.io.File;
import koulutusRekisteri.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.05.20 16:40:09 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class RelaatiotTest {


  // Generated by ComTest BEGIN
  /** 
   * testPoista58 
   * @throws SailoException when error
   */
  @Test
  public void testPoista58() throws SailoException {    // Relaatiot: 58
    Relaatiot relaatiot = new Relaatiot(); 
    Relaatio rel1 = new Relaatio(), rel2 = new Relaatio(), rel3 = new Relaatio(); 
    rel1.rekisteroi(); rel2.rekisteroi(); rel3.rekisteroi(); 
    int id1 = rel1.getRelaatioTunnus(); 
    relaatiot.lisaa(rel1); relaatiot.lisaa(rel2); relaatiot.lisaa(rel3); 
    assertEquals("From: Relaatiot line: 65", 1, relaatiot.poista(id1+1)); 
    assertEquals("From: Relaatiot line: 66", null, relaatiot.annaRelaatiot(id1+1)); assertEquals("From: Relaatiot line: 66", 2, relaatiot.getLkm()); 
    assertEquals("From: Relaatiot line: 67", 1, relaatiot.poista(id1)); assertEquals("From: Relaatiot line: 67", 1, relaatiot.getLkm()); 
    assertEquals("From: Relaatiot line: 68", 0, relaatiot.poista(id1+3)); assertEquals("From: Relaatiot line: 68", 1, relaatiot.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testEtsiId91 
   * @throws SailoException when error
   */
  @Test
  public void testEtsiId91() throws SailoException {    // Relaatiot: 91
    Relaatiot relaatiot = new Relaatiot(); 
    Relaatio rel1 = new Relaatio(), rel2 = new Relaatio(), rel3 = new Relaatio(); 
    rel1.rekisteroi(); rel2.rekisteroi(); rel3.rekisteroi(); 
    int id1 = rel1.getRelaatioTunnus(); 
    relaatiot.lisaa(rel1); relaatiot.lisaa(rel2); relaatiot.lisaa(rel3); 
    assertEquals("From: Relaatiot line: 98", 1, relaatiot.etsiId(id1+1)); 
    assertEquals("From: Relaatiot line: 99", 2, relaatiot.etsiId(id1+2)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLisaa115 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa115() throws SailoException {    // Relaatiot: 115
    Relaatiot relaatiot = new Relaatiot(); 
    Relaatio rel1 = new Relaatio(), rel2 = new Relaatio(); 
    assertEquals("From: Relaatiot line: 120", 0, relaatiot.getLkm()); 
    relaatiot.lisaa(rel1); assertEquals("From: Relaatiot line: 121", 1, relaatiot.getLkm()); 
    relaatiot.lisaa(rel2); assertEquals("From: Relaatiot line: 122", 2, relaatiot.getLkm()); 
    relaatiot.lisaa(rel1); assertEquals("From: Relaatiot line: 123", 3, relaatiot.getLkm()); 
    assertEquals("From: Relaatiot line: 124", rel1, relaatiot.annaRelaatiot(0)); 
    assertEquals("From: Relaatiot line: 125", rel2, relaatiot.annaRelaatiot(1)); 
    assertEquals("From: Relaatiot line: 126", rel1, relaatiot.annaRelaatiot(2)); 
    assertEquals("From: Relaatiot line: 127", false, relaatiot.annaRelaatiot(1) == rel1); 
    assertEquals("From: Relaatiot line: 128", true, relaatiot.annaRelaatiot(1) == rel2); 
    try {
    assertEquals("From: Relaatiot line: 129", rel1, relaatiot.annaRelaatiot(3)); 
    fail("Relaatiot: 129 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    relaatiot.lisaa(rel1); assertEquals("From: Relaatiot line: 130", 4, relaatiot.getLkm()); 
    relaatiot.lisaa(rel1); assertEquals("From: Relaatiot line: 131", 5, relaatiot.getLkm()); 
    try {
    relaatiot.lisaa(rel1); 
    fail("Relaatiot: 132 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta168 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta168() throws SailoException {    // Relaatiot: 168
    Relaatiot relaatiot = new Relaatiot(); 
    Relaatio rel1 = new Relaatio(), rel2 = new Relaatio(); 
    rel1.vastaaRelaatio(); 
    rel2.vastaaRelaatio(); 
    String hakemisto = "testirelaatiot"; 
    String tiedNimi = hakemisto+"/relaatiot"; 
    File ftied = new File(tiedNimi+".dat"); 
    File dir = new File(hakemisto); 
    dir.mkdir(); 
    ftied.delete(); 
    try {
    relaatiot.lueTiedostosta(tiedNimi); 
    fail("Relaatiot: 183 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    relaatiot.lisaa(rel1); 
    relaatiot.lisaa(rel2); 
    relaatiot.tallenna(); 
    relaatiot = new Relaatiot(); 
    relaatiot.lueTiedostosta(tiedNimi); 
    Iterator<Relaatio> i = relaatiot.iterator(); 
    assertEquals("From: Relaatiot line: 191", rel1, i.next()); 
    assertEquals("From: Relaatiot line: 192", rel2, i.next()); 
    assertEquals("From: Relaatiot line: 193", false, i.hasNext()); 
    relaatiot.lisaa(rel2); 
    relaatiot.tallenna(); 
    assertEquals("From: Relaatiot line: 196", true, ftied.delete()); 
    assertEquals("From: Relaatiot line: 197", true, dir.delete()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testRelaatiotIterator323 
   * @throws SailoException when error
   */
  @Test
  public void testRelaatiotIterator323() throws SailoException {    // Relaatiot: 323
    Relaatiot relaatiot = new Relaatiot(); 
    Relaatio rel1 = new Relaatio(), rel2 = new Relaatio(); 
    rel1.rekisteroi(); rel2.rekisteroi(); 
    relaatiot.lisaa(rel1); 
    relaatiot.lisaa(rel2); 
    relaatiot.lisaa(rel1); 
    StringBuffer ids = new StringBuffer(30); 
    for (Relaatio relaatio:relaatiot)
    ids.append(" "+relaatio.getRelaatioTunnus()); 
    String tulos = " " + rel1.getRelaatioTunnus() + " " + rel2.getRelaatioTunnus() + " " + rel1.getRelaatioTunnus(); 
    assertEquals("From: Relaatiot line: 342", tulos, ids.toString()); 
    ids = new StringBuffer(30); 
    for (Iterator<Relaatio> i=relaatiot.iterator(); i.hasNext(); ) {
    Relaatio relaatio = i.next(); 
    ids.append(" "+relaatio.getRelaatioTunnus()); 
    }
    assertEquals("From: Relaatiot line: 350", tulos, ids.toString()); 
    Iterator<Relaatio> i=relaatiot.iterator(); 
    assertEquals("From: Relaatiot line: 353", true, i.next() == rel1); 
    assertEquals("From: Relaatiot line: 354", true, i.next() == rel2); 
    assertEquals("From: Relaatiot line: 355", true, i.next() == rel1); 
    try {
    i.next(); 
    fail("Relaatiot: 357 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testIterator419 */
  @Test
  public void testIterator419() {    // Relaatiot: 419
    Relaatiot relaatiot = new Relaatiot(); 
    try {
    Relaatio rel1 = new Relaatio(); rel1.rekisteroi(); relaatiot.lisaa(rel1); 
    fail("Relaatiot: 425 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    try {
    Relaatio rel2 = new Relaatio(); rel2.rekisteroi(); relaatiot.lisaa(rel2); 
    fail("Relaatiot: 426 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    try {
    Relaatio rel3 = new Relaatio(); rel3.rekisteroi(); relaatiot.lisaa(rel3); 
    fail("Relaatiot: 427 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    int n = 0; 
    int jnrot[] = { 1,2,3} ; 
    for (Relaatio rel:relaatiot) {
    assertEquals("From: Relaatiot line: 433", jnrot[n], rel.getTyontekijaTunnus()); n++; 
    }
    assertEquals("From: Relaatiot line: 436", 3, n); 
  } // Generated by ComTest END
}