package koulutusRekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import koulutusRekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.05.26 20:02:43 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class RelaatioTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi128 */
  @Test
  public void testRekisteroi128() {    // Relaatio: 128
    Relaatio rel1 = new Relaatio(); 
    assertEquals("From: Relaatio line: 130", 0, rel1.getRelaatioTunnus()); 
    rel1.rekisteroi(); 
    Relaatio rel2 = new Relaatio(); 
    rel2.rekisteroi(); 
    int n1 = rel1.getRelaatioTunnus(); 
    int n2 = rel2.getRelaatioTunnus(); 
    assertEquals("From: Relaatio line: 136", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString246 */
  @Test
  public void testToString246() {    // Relaatio: 246
    Relaatio relaatio = new Relaatio(); 
    relaatio.parse("   1   |  1  |   1  | Vesisukeltaja | 1.1.2021 | 1.1.2031 "); 
    assertEquals("From: Relaatio line: 249", "1|1|1|Vesisukeltaja|1.1.2021|1.1.2031", relaatio.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse263 */
  @Test
  public void testParse263() {    // Relaatio: 263
    Relaatio relaatio = new Relaatio(); 
    relaatio.parse("   1   |  1  |   1  |Vesisukeltaja | 1.1.2021 | 1.1.2031 "); 
    assertEquals("From: Relaatio line: 266", 1, relaatio.getRelaatioTunnus()); 
    assertEquals("From: Relaatio line: 267", "1|1|1|Vesisukeltaja|1.1.2021|1.1.2031", relaatio.toString()); 
    relaatio.rekisteroi(); 
    int n = relaatio.getRelaatioTunnus(); 
    relaatio.parse(""+(n+20)); 
    relaatio.rekisteroi(); 
    assertEquals("From: Relaatio line: 273", n+20+1, relaatio.getRelaatioTunnus()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone291 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone291() throws CloneNotSupportedException {    // Relaatio: 291
    Relaatio relaatio = new Relaatio(); 
    relaatio.parse("   1   |  1  |   1  |Vesisukeltaja | 1.1.2021 | 1.1.2031 "); 
    Relaatio kopio = relaatio.clone(); 
    assertEquals("From: Relaatio line: 296", relaatio.toString(), kopio.toString()); 
    relaatio.parse("   2   |  1  |   1  |Vesisukeltaja | 1.1.2021 | 1.1.2031 "); 
    assertEquals("From: Relaatio line: 298", false, kopio.toString().equals(relaatio.toString())); 
  } // Generated by ComTest END
}