package koulutusRekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import koulutusRekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.05.05 18:11:35 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class RelaatioTest {


  // Generated by ComTest BEGIN
  /** testRekisteroi87 */
  @Test
  public void testRekisteroi87() {    // Relaatio: 87
    Relaatio rel1 = new Relaatio(); 
    assertEquals("From: Relaatio line: 89", 0, rel1.getRelaatioTunnus()); 
    rel1.rekisteroi(); 
    Relaatio rel2 = new Relaatio(); 
    rel2.rekisteroi(); 
    int n1 = rel1.getRelaatioTunnus(); 
    int n2 = rel2.getRelaatioTunnus(); 
    assertEquals("From: Relaatio line: 95", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString185 */
  @Test
  public void testToString185() {    // Relaatio: 185
    Relaatio relaatio = new Relaatio(); 
    relaatio.parse("   1   |  1  |   1  | 1.1.2021 | 1.1.2031 "); 
    assertEquals("From: Relaatio line: 188", "1|1|1|1.1.2021|1.1.2031", relaatio.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse202 */
  @Test
  public void testParse202() {    // Relaatio: 202
    Relaatio relaatio = new Relaatio(); 
    relaatio.parse("   1   |  1  |   1  | 1.1.2021 | 1.1.2031 "); 
    assertEquals("From: Relaatio line: 205", 1, relaatio.getRelaatioTunnus()); 
    assertEquals("From: Relaatio line: 206", "1|1|1|1.1.2021|1.1.2031", relaatio.toString()); 
    relaatio.rekisteroi(); 
    int n = relaatio.getRelaatioTunnus(); 
    relaatio.parse(""+(n+20)); 
    relaatio.rekisteroi(); 
    assertEquals("From: Relaatio line: 212", n+20+1, relaatio.getRelaatioTunnus()); 
  } // Generated by ComTest END
}