package koulutusRekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import koulutusRekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.05.20 16:36:29 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class RelaatioTest {


  // Generated by ComTest BEGIN
  /** testRekisteroi84 */
  @Test
  public void testRekisteroi84() {    // Relaatio: 84
    Relaatio rel1 = new Relaatio(); 
    assertEquals("From: Relaatio line: 86", 0, rel1.getRelaatioTunnus()); 
    rel1.rekisteroi(); 
    Relaatio rel2 = new Relaatio(); 
    rel2.rekisteroi(); 
    int n1 = rel1.getRelaatioTunnus(); 
    int n2 = rel2.getRelaatioTunnus(); 
    assertEquals("From: Relaatio line: 92", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString193 */
  @Test
  public void testToString193() {    // Relaatio: 193
    Relaatio relaatio = new Relaatio(); 
    relaatio.parse("   1   |  1  |   1  | 1.1.2021 | 1.1.2031 "); 
    assertEquals("From: Relaatio line: 196", "1|1|1|1.1.2021|1.1.2031", relaatio.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse210 */
  @Test
  public void testParse210() {    // Relaatio: 210
    Relaatio relaatio = new Relaatio(); 
    relaatio.parse("   1   |  1  |   1  | 1.1.2021 | 1.1.2031 "); 
    assertEquals("From: Relaatio line: 213", 1, relaatio.getRelaatioTunnus()); 
    assertEquals("From: Relaatio line: 214", "1|1|1|1.1.2021|1.1.2031", relaatio.toString()); 
    relaatio.rekisteroi(); 
    int n = relaatio.getRelaatioTunnus(); 
    relaatio.parse(""+(n+20)); 
    relaatio.rekisteroi(); 
    assertEquals("From: Relaatio line: 220", n+20+1, relaatio.getRelaatioTunnus()); 
  } // Generated by ComTest END
}