package koulutusRekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import koulutusRekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.05.26 19:53:54 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class TyontekijaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi143 */
  @Test
  public void testRekisteroi143() {    // Tyontekija: 143
    Tyontekija aku1 = new Tyontekija(); 
    assertEquals("From: Tyontekija line: 145", 0, aku1.getTyontekijaTunnus()); 
    aku1.rekisteroi(); 
    Tyontekija aku2 = new Tyontekija(); 
    aku2.rekisteroi(); 
    int n1 = aku1.getTyontekijaTunnus(); 
    int n2 = aku2.getTyontekijaTunnus(); 
    assertEquals("From: Tyontekija line: 151", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetNimi200 */
  @Test
  public void testGetNimi200() {    // Tyontekija: 200
    Tyontekija aku = new Tyontekija(); 
    aku.vastaaAkuAnkka(); 
    { String _l_=aku.getNimi(),_r_="Ankka Aku"; if ( !_l_.matches(_r_) ) fail("From: Tyontekija line: 203" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString226 */
  @Test
  public void testToString226() {    // Tyontekija: 226
    Tyontekija tyontekija = new Tyontekija(); 
    tyontekija.parse("   1  |  Ankka Aku   | Pelastustoiminta | Palomies "); 
    assertEquals("From: Tyontekija line: 229", "1|Ankka Aku|Pelastustoiminta|Palomies", tyontekija.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse243 */
  @Test
  public void testParse243() {    // Tyontekija: 243
    Tyontekija tyontekija = new Tyontekija(); 
    tyontekija.parse("   1  |  Ankka Aku   | Pelastustoiminta | Palomies "); 
    assertEquals("From: Tyontekija line: 246", 1, tyontekija.getTyontekijaTunnus()); 
    assertEquals("From: Tyontekija line: 247", "1|Ankka Aku|Pelastustoiminta|Palomies", tyontekija.toString()); 
    tyontekija.rekisteroi(); 
    int n = tyontekija.getTyontekijaTunnus(); 
    tyontekija.parse(""+(n+20)); 
    tyontekija.rekisteroi(); 
    assertEquals("From: Tyontekija line: 253", n+20+1, tyontekija.getTyontekijaTunnus()); 
    assertEquals("From: Tyontekija line: 254", "" + (n+20+1) + "|Ankka Aku|Pelastustoiminta|Palomies", tyontekija.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone270 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone270() throws CloneNotSupportedException {    // Tyontekija: 270
    Tyontekija tyontekija = new Tyontekija(); 
    tyontekija.parse("   3  |  Ankka Aku   | 123"); 
    Tyontekija kopio = tyontekija.clone(); 
    assertEquals("From: Tyontekija line: 275", tyontekija.toString(), kopio.toString()); 
    tyontekija.parse("   4  |  Ankka Tupu   | 123"); 
    assertEquals("From: Tyontekija line: 277", false, kopio.toString().equals(tyontekija.toString())); 
  } // Generated by ComTest END
}