package koulutusRekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import koulutusRekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.05.05 17:49:14 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class TyontekijaTest {


  // Generated by ComTest BEGIN
  /** testRekisteroi102 */
  @Test
  public void testRekisteroi102() {    // Tyontekija: 102
    Tyontekija aku1 = new Tyontekija(); 
    assertEquals("From: Tyontekija line: 104", 0, aku1.getTyontekijaTunnus()); 
    aku1.rekisteroi(); 
    Tyontekija aku2 = new Tyontekija(); 
    aku2.rekisteroi(); 
    int n1 = aku1.getTyontekijaTunnus(); 
    int n2 = aku2.getTyontekijaTunnus(); 
    assertEquals("From: Tyontekija line: 110", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetNimi132 */
  @Test
  public void testGetNimi132() {    // Tyontekija: 132
    Tyontekija aku = new Tyontekija(); 
    aku.vastaaAkuAnkka(); 
    { String _l_=aku.getNimi(),_r_="Ankka Aku .*"; if ( !_l_.matches(_r_) ) fail("From: Tyontekija line: 135" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString158 */
  @Test
  public void testToString158() {    // Tyontekija: 158
    Tyontekija tyontekija = new Tyontekija(); 
    tyontekija.parse("   1  |  Ankka Aku   | Pelastustoiminta | Palomies "); 
    assertEquals("From: Tyontekija line: 161", "1|Ankka Aku|Pelastustoiminta|Palomies", tyontekija.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse179 */
  @Test
  public void testParse179() {    // Tyontekija: 179
    Tyontekija tyontekija = new Tyontekija(); 
    tyontekija.parse("   1  |  Ankka Aku   | Pelastustoiminta | Palomies "); 
    assertEquals("From: Tyontekija line: 182", 1, tyontekija.getTyontekijaTunnus()); 
    assertEquals("From: Tyontekija line: 183", "1|Ankka Aku|Pelastustoiminta|Palomies", tyontekija.toString()); 
    tyontekija.rekisteroi(); 
    int n = tyontekija.getTyontekijaTunnus(); 
    tyontekija.parse(""+(n+20)); 
    tyontekija.rekisteroi(); 
    assertEquals("From: Tyontekija line: 189", n+20+1, tyontekija.getTyontekijaTunnus()); 
    assertEquals("From: Tyontekija line: 190", "" + (n+20+1) + "|Ankka Aku|Pelastustoiminta|Palomies", tyontekija.toString()); 
  } // Generated by ComTest END
}