package koulutusRekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import koulutusRekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.02.27 21:33:07 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class TyontekijaTest {


  // Generated by ComTest BEGIN
  /** testLisaaTyontekija57 */
  @Test
  public void testLisaaTyontekija57() {    // Tyontekija: 57
    Tyontekija aku1 = new Tyontekija(); 
    assertEquals("From: Tyontekija line: 59", 0, aku1.getTyontekijaTunnus()); 
    aku1.lisaaTyontekija(); 
    Tyontekija aku2 = new Tyontekija(); 
    aku2.lisaaTyontekija(); 
    int n1 = aku1.getTyontekijaTunnus(); 
    int n2 = aku2.getTyontekijaTunnus(); 
    assertEquals("From: Tyontekija line: 65", n2-1, n1); 
  } // Generated by ComTest END
}